### ISSUE TITLE
Error 500 when adding organization user

### ISSUE THREAD

**Issue by jahknem** [openwisp/openwisp-radius#516]
When trying to add an organization owner, there is no multiple choice field of valid users. Instead there is only a freeform text field. When writing a user into that field we get error 500.

I can see that it works in the demo instance, so maybe this is an error when installing just the radius role via ansible installer?

Installed via ansible with this playbook:

```
- hosts: openwisp2
  remote_user: snip
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  # the following line is needed only when an IP address is used as the inventory hostname
  vars:
    openwisp2_default_from_email: "snip"
    openwisp2_radius: true
    openwisp2_freeradius_install: true
    # set to false when you don't want to register openwisp-radius
    # API endpoints.
    openwisp2_radius_urls: true
    openwisp2_monitoring: false
    openwisp2_postfix_install: true
```
The host is an ubuntu vm. No further changes except for the configuration of postfix (smart host) were made on the system.
